[profile.default]
src = "src"
out = "out"
libs = []
# via_ir = true
optimizer = true
optimizer_runs = 200
allow_paths = [
    "../../node_modules/forge-std",
    "../../protocol/synthetix",
    "../../utils/core-contracts",
]
remappings = [
    "forge-std=../../node_modules/forge-std/src",
    "@synthetixio=../../node_modules/@synthetixio",
]

fs_permissions = [{ access = "read", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
